apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer  # Используйте NodePort, если вы не находитесь в облаке
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx